//
//  String Keys.swift
//  MovieStar
//
//  Created by obss on 5.07.2022.
//

import Foundation
struct StringKey{
    static let infoTitle = "Movie Information".localized()
    static let prodTitle = "Production Companies".localized()
    static let castTitle = "Cast".localized()
    static let recomTitle = "Recommended Movies".localized()
    static let genreTitle = "Genres".localized()
    static let listPageHeader = "Movie List".localized()
    static let searchPageHeader = "Search".localized()
    static let favoritesPageHeader = "Favorites".localized()
    static let error = "Error".localized()
    static let ok = "OK".localized()
    static let search = "Search".localized()
    static let infoMessage = "Information Message".localized()
    static let homepage = "Homepage has not found!".localized()
    static let favoriteEmpty = "Your favorite list is empty, you can add your new movies from the detail page. For adding new movies just hit the heart icon!".localized()
    static let refresh = "Pull to refresh".localized()
    static let searchMessage = "Please touch the search area for searching movies...".localized()
    static let noDetail = "Movie details has not found!".localized()
    static let noMovie = "Movie has not found!".localized()
    static let overview = "Overview:".localized()
    static let noOverview = "Overview has not found.".localized()
    static let orgLang = "Original Lang: ".localized()
    static let unLanguage = "Unknown language.".localized()
    static let orgTitle = "Original Title: ".localized()
    static let unTitle = "Unknown title.".localized()
    static let releaseDate = "Release Date: ".localized()
    static let unRelease = "Release date has not founded.".localized()
    static let budget = "Budget: ".localized()
    static let unBudget = "Unkown budget!".localized()
    static let revenue = "Revenue: ".localized()
    static let unRevenue = "Unknown revenue!".localized()
    static let runtime = "Runtime: ".localized()
    static let minute = " min".localized()
    static let unRuntime = "Unknown runtime!".localized()
    static let unName = "Unknown movie name!".localized()
    static let unknownRelease = "Unknown movie release date!".localized()
    static let favoriteButtonAlert = "Movie has already added the favorite list. If you want to remove the movie please touch the Remove! button".localized()
    static let remove = "Remove!".localized()
    static let favError = "Movie can not added to favorite list!".localized()
    static let noPerson = "Person has not found!".localized()
    static let notRanked = "Not ranked yet!".localized()
    static let unValue = "Unknown value".localized()
    static let birthday = "Birthday: ".localized()
    static let deathday = "Deathday: ".localized()
    static let placeOfBirth = "Place of birth: ".localized()
    static let bio = "Biography: ".localized()
    static let emptyContent = "Content has not found!".localized()
    static let translateError = "There is no content suitable for the language option used.".localized()
}
